# Generated by Django 3.2.5 on 2021-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211105_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='iteam',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='', max_length=5),
        ),
    ]
