# Generated by Django 3.2.5 on 2021-11-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211105_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='iteam',
            field=models.CharField(max_length=25),
        ),
    ]
