# Generated by Django 3.2.5 on 2021-11-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0011_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=5)),
                ('quantity', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
    ]
