# Generated by Django 3.2.5 on 2021-11-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211106_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iteam',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=5),
        ),
    ]
